Deparallelize percy, remove dupe URLs and use standard chrome driver.

diff --git a/tools/release_automation/percy_snapshot_script/cloudbuild.per_environment_percy_snapshots.yaml b/tools/release_automation/percy_snapshot_script/cloudbuild.per_environment_percy_snapshots.yaml
--- a/tools/release_automation/percy_snapshot_script/cloudbuild.per_environment_percy_snapshots.yaml
+++ b/tools/release_automation/percy_snapshot_script/cloudbuild.per_environment_percy_snapshots.yaml
@@ -175,7 +175,8 @@ steps:
         cd /app
         export PERCY_TOKEN="$percy_token"
         export PERCY_PARALLEL_NONCE="${BUILD_ID}"
-        percy build:finalize
+        # Finalize the build; ignore errors to avoid failing the build if there are visual diffs.
+        percy build:finalize || true
     secretEnv: ['percy_token']
 
 availableSecrets:
